# Generated by Django 5.2.1 on 2025-09-04 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0002_memorialpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flower_type', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('memorial_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='memorial.memorialpage')),
            ],
        ),
    ]
